version: "3.8"

services:
  snitchvis:
    # build: .
    image: ghcr.io/kingcolton1/snitchvis-docker:latest
    # environment:
    restart: always
    # stdin_open: true
    # tty: true
    # init: true
    volumes:
      # make sure config.py exist before running docker-compose
      - ./config.py:/app/config.py:ro
      - snitchvisdb:/app/snitchvis.db # testing
      # xserver
      # - /tmp/.X11-unix:/tmp/.X11-unix
volumes:
  snitchvisdb:
